return {
    version = 1,
    name = "Map 2: Delayed Button",
    template = true,
    editor = {
        endpoints = {
            { id = "left_in_mint", kind = "input", x = 0.1422, y = 0.0583, colors = { "mint" } },
            { id = "left_in_rose", kind = "input", x = 0.2828, y = 0.0583, colors = { "rose" } },
            { id = "left_out", kind = "output", x = 0.2125, y = 0.9722, colors = { "mint", "rose" } },
            { id = "right_in_blue", kind = "input", x = 0.4516, y = 0.0583, colors = { "blue" } },
            { id = "right_in_yellow", kind = "input", x = 0.5922, y = 0.0583, colors = { "yellow" } },
            { id = "right_out", kind = "output", x = 0.5219, y = 0.9722, colors = { "blue", "yellow" } },
        },
        routes = {
            {
                id = "left_route_mint",
                label = "Mint",
                color = "mint",
                startEndpointId = "left_in_mint",
                endEndpointId = "left_out",
                points = {
                    { x = 0.1422, y = 0.0583 },
                    { x = 0.1422, y = 0.2922 },
                    { x = 0.2125, y = 0.5000 },
                    { x = 0.2125, y = 0.9722 },
                },
            },
            {
                id = "left_route_rose",
                label = "Rose",
                color = "rose",
                startEndpointId = "left_in_rose",
                endEndpointId = "left_out",
                points = {
                    { x = 0.2828, y = 0.0583 },
                    { x = 0.2828, y = 0.2922 },
                    { x = 0.2125, y = 0.5000 },
                    { x = 0.2125, y = 0.9722 },
                },
            },
            {
                id = "right_route_blue",
                label = "Blue",
                color = "blue",
                startEndpointId = "right_in_blue",
                endEndpointId = "right_out",
                points = {
                    { x = 0.4516, y = 0.0583 },
                    { x = 0.4516, y = 0.2922 },
                    { x = 0.5219, y = 0.5000 },
                    { x = 0.5219, y = 0.9722 },
                },
            },
            {
                id = "right_route_yellow",
                label = "Gold",
                color = "yellow",
                startEndpointId = "right_in_yellow",
                endEndpointId = "right_out",
                points = {
                    { x = 0.5922, y = 0.0583 },
                    { x = 0.5922, y = 0.2922 },
                    { x = 0.5219, y = 0.5000 },
                    { x = 0.5219, y = 0.9722 },
                },
            },
        },
        junctions = {
            {
                id = "junction_left",
                x = 0.2125,
                y = 0.5000,
                control = "direct",
                activeInputIndex = 1,
                activeOutputIndex = 1,
                routes = { "left_route_mint", "left_route_rose" },
                inputEndpointIds = { "left_in_mint", "left_in_rose" },
                outputEndpointIds = { "left_out" },
            },
            {
                id = "junction_right",
                x = 0.5219,
                y = 0.5000,
                control = "delayed",
                activeInputIndex = 1,
                activeOutputIndex = 1,
                routes = { "right_route_blue", "right_route_yellow" },
                inputEndpointIds = { "right_in_blue", "right_in_yellow" },
                outputEndpointIds = { "right_out" },
            },
        },
    },
    level = {
        title = "Map 2: Delayed Button",
        description = "Two merges, four trains, and a timer. The left crossing flips instantly, the right button swaps after a delay.",
        hint = "Arm the delayed button early so the second right-side train gets its route in time.",
        footer = "Clear all four trains before the timer expires. The delayed swap only happens after its countdown finishes.",
        timeLimit = 15,
        junctions = {
            {
                id = "left_direct",
                activeInputIndex = 1,
                activeOutputIndex = 1,
                control = {
                    type = "direct",
                    label = "Direct Lever",
                },
                inputs = {
                    {
                        id = "left_route_mint_input",
                        label = "Input 1",
                        colors = { "mint" },
                        color = { 0.40, 0.92, 0.76 },
                        darkColor = { 0.12, 0.38, 0.31 },
                        inputPoints = {
                            { x = 0.1422, y = 0.0583 },
                            { x = 0.1422, y = 0.2922 },
                            { x = 0.2125, y = 0.5000 },
                        },
                    },
                    {
                        id = "left_route_rose_input",
                        label = "Input 2",
                        colors = { "rose" },
                        color = { 0.98, 0.48, 0.62 },
                        darkColor = { 0.42, 0.14, 0.22 },
                        inputPoints = {
                            { x = 0.2828, y = 0.0583 },
                            { x = 0.2828, y = 0.2922 },
                            { x = 0.2125, y = 0.5000 },
                        },
                    },
                },
                outputs = {
                    {
                        id = "left_out",
                        label = "Output 1",
                        colors = { "mint", "rose" },
                        color = { 0.40, 0.92, 0.76 },
                        darkColor = { 0.12, 0.38, 0.31 },
                        adoptInputColor = true,
                        outputPoints = {
                            { x = 0.2125, y = 0.5000 },
                            { x = 0.2125, y = 0.9722 },
                        },
                    },
                },
            },
            {
                id = "right_delayed",
                activeInputIndex = 1,
                activeOutputIndex = 1,
                control = {
                    type = "delayed",
                    label = "Delayed Button",
                    delay = 2.25,
                },
                inputs = {
                    {
                        id = "right_route_blue_input",
                        label = "Input 1",
                        colors = { "blue" },
                        color = { 0.33, 0.80, 0.98 },
                        darkColor = { 0.12, 0.32, 0.44 },
                        inputPoints = {
                            { x = 0.4516, y = 0.0583 },
                            { x = 0.4516, y = 0.2922 },
                            { x = 0.5219, y = 0.5000 },
                        },
                    },
                    {
                        id = "right_route_yellow_input",
                        label = "Input 2",
                        colors = { "yellow" },
                        color = { 0.98, 0.82, 0.34 },
                        darkColor = { 0.46, 0.34, 0.08 },
                        inputPoints = {
                            { x = 0.5922, y = 0.0583 },
                            { x = 0.5922, y = 0.2922 },
                            { x = 0.5219, y = 0.5000 },
                        },
                    },
                },
                outputs = {
                    {
                        id = "right_out",
                        label = "Output 1",
                        colors = { "blue", "yellow" },
                        color = { 0.33, 0.80, 0.98 },
                        darkColor = { 0.12, 0.32, 0.44 },
                        adoptInputColor = true,
                        outputPoints = {
                            { x = 0.5219, y = 0.5000 },
                            { x = 0.5219, y = 0.9722 },
                        },
                    },
                },
            },
        },
        trains = {
            { id = "left_mint_train", junctionId = "left_direct", inputIndex = 1, progress = -40, speedScale = 1.0, color = { 0.40, 0.92, 0.76 } },
            { id = "left_rose_train", junctionId = "left_direct", inputIndex = 2, progress = -175, speedScale = 0.96, color = { 0.98, 0.48, 0.62 } },
            { id = "right_blue_train", junctionId = "right_delayed", inputIndex = 1, progress = -60, speedScale = 1.0, color = { 0.33, 0.80, 0.98 } },
            { id = "right_gold_train", junctionId = "right_delayed", inputIndex = 2, progress = -205, speedScale = 0.95, color = { 0.98, 0.82, 0.34 } },
        },
    },
}
