return {
    version = 1,
    mapUuid = "e806cef3-7f32-482d-a367-acaa5e470545",
    name = "Map 7: Crossbar Dial",
    previewDescription = "The active input is always routed to the mirrored exit.",
    template = true,
    editor = {
        endpoints = {
            { id = "in_blue", kind = "input", x = 0.1664, y = 0.0583, colors = { "blue" } },
            { id = "in_mint", kind = "input", x = 0.3672, y = 0.0583, colors = { "mint" } },
            { id = "in_yellow", kind = "input", x = 0.5680, y = 0.0583, colors = { "yellow" } },
            { id = "out_left", kind = "output", x = 0.1664, y = 0.9722, colors = { "blue", "mint", "yellow" } },
            { id = "out_center", kind = "output", x = 0.3672, y = 0.9722, colors = { "blue", "mint", "yellow" } },
            { id = "out_right", kind = "output", x = 0.5680, y = 0.9722, colors = { "blue", "mint", "yellow" } },
        },
        routes = {
            {
                id = "route_blue",
                label = "Blue",
                color = "blue",
                startEndpointId = "in_blue",
                endEndpointId = "out_right",
                points = {
                    { x = 0.1664, y = 0.0583 },
                    { x = 0.1664, y = 0.2681 },
                    { x = 0.3672, y = 0.4556 },
                    { x = 0.5680, y = 0.7111 },
                    { x = 0.5680, y = 0.9722 },
                },
            },
            {
                id = "route_mint",
                label = "Mint",
                color = "mint",
                startEndpointId = "in_mint",
                endEndpointId = "out_center",
                points = {
                    { x = 0.3672, y = 0.0583 },
                    { x = 0.3672, y = 0.2403 },
                    { x = 0.3672, y = 0.4556 },
                    { x = 0.3672, y = 0.9722 },
                },
            },
            {
                id = "route_yellow",
                label = "Gold",
                color = "yellow",
                startEndpointId = "in_yellow",
                endEndpointId = "out_left",
                points = {
                    { x = 0.5680, y = 0.0583 },
                    { x = 0.5680, y = 0.2681 },
                    { x = 0.3672, y = 0.4556 },
                    { x = 0.1664, y = 0.7111 },
                    { x = 0.1664, y = 0.9722 },
                },
            },
        },
        junctions = {
            {
                id = "junction_crossbar",
                x = 0.3672,
                y = 0.4556,
                control = "crossbar",
                activeInputIndex = 3,
                activeOutputIndex = 1,
                routes = { "route_blue", "route_mint", "route_yellow" },
                inputEndpointIds = { "in_blue", "in_mint", "in_yellow" },
                outputEndpointIds = { "out_left", "out_center", "out_right" },
            },
        },
    },
    level = {
        title = "Map 7: Crossbar Dial",
        previewDescription = "The active input is always routed to the mirrored exit.",
        description = "The crossbar dial links the chosen input to the opposite side of the yard, with the center lane mirroring to itself.",
        hint = "Start with gold already lined for the left exit. Then click forward for blue on the right, then once more for mint down the center.",
        footer = "Crossbar dials mirror lane numbers. They choose the opposite exit automatically and lock the output selector.",
        junctions = {
            {
                id = "crossbar_tutorial",
                activeInputIndex = 3,
                activeOutputIndex = 1,
                control = {
                    type = "crossbar",
                    label = "Crossbar Dial",
                },
                inputs = {
                    {
                        id = "route_blue_input",
                        label = "Input 1",
                        colors = { "blue" },
                        color = { 0.33, 0.80, 0.98 },
                        darkColor = { 0.12, 0.32, 0.44 },
                        inputPoints = {
                            { x = 0.1664, y = 0.0583 },
                            { x = 0.1664, y = 0.2681 },
                            { x = 0.3672, y = 0.4556 },
                        },
                    },
                    {
                        id = "route_mint_input",
                        label = "Input 2",
                        colors = { "mint" },
                        color = { 0.40, 0.92, 0.76 },
                        darkColor = { 0.12, 0.38, 0.31 },
                        inputPoints = {
                            { x = 0.3672, y = 0.0583 },
                            { x = 0.3672, y = 0.2403 },
                            { x = 0.3672, y = 0.4556 },
                        },
                    },
                    {
                        id = "route_yellow_input",
                        label = "Input 3",
                        colors = { "yellow" },
                        color = { 0.98, 0.82, 0.34 },
                        darkColor = { 0.46, 0.34, 0.08 },
                        inputPoints = {
                            { x = 0.5680, y = 0.0583 },
                            { x = 0.5680, y = 0.2681 },
                            { x = 0.3672, y = 0.4556 },
                        },
                    },
                },
                outputs = {
                    {
                        id = "out_left",
                        label = "Output 1",
                        colors = { "blue", "mint", "yellow" },
                        color = { 0.98, 0.82, 0.34 },
                        darkColor = { 0.46, 0.34, 0.08 },
                        adoptInputColor = true,
                        outputPoints = {
                            { x = 0.3672, y = 0.4556 },
                            { x = 0.1664, y = 0.7111 },
                            { x = 0.1664, y = 0.9722 },
                        },
                    },
                    {
                        id = "out_center",
                        label = "Output 2",
                        colors = { "blue", "mint", "yellow" },
                        color = { 0.40, 0.92, 0.76 },
                        darkColor = { 0.12, 0.38, 0.31 },
                        adoptInputColor = true,
                        outputPoints = {
                            { x = 0.3672, y = 0.4556 },
                            { x = 0.3672, y = 0.9722 },
                        },
                    },
                    {
                        id = "out_right",
                        label = "Output 3",
                        colors = { "blue", "mint", "yellow" },
                        color = { 0.33, 0.80, 0.98 },
                        darkColor = { 0.12, 0.32, 0.44 },
                        adoptInputColor = true,
                        outputPoints = {
                            { x = 0.3672, y = 0.4556 },
                            { x = 0.5680, y = 0.7111 },
                            { x = 0.5680, y = 0.9722 },
                        },
                    },
                },
            },
        },
        trains = {
            { id = "crossbar_gold_train", junctionId = "crossbar_tutorial", inputIndex = 3, progress = -86, speedScale = 1.0, color = { 0.98, 0.82, 0.34 } },
            { id = "crossbar_blue_train", junctionId = "crossbar_tutorial", inputIndex = 1, progress = -178, speedScale = 0.97, color = { 0.33, 0.80, 0.98 } },
            { id = "crossbar_mint_train", junctionId = "crossbar_tutorial", inputIndex = 2, progress = -294, speedScale = 0.93, color = { 0.40, 0.92, 0.76 } },
        },
    },
}
